global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'timesheet-backend'
    metrics_path: '/timesheet-devops/actuator/prometheus'
    static_configs:
      - targets: ['timesheet-backend:8082']